apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T13:10:47Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1597"
  uid: 82e3a03c-129b-4cf8-995b-26dff2cb91b4
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.212.82
  clusterIPs:
  - 10.110.212.82
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30106
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
